Add tests
thgh/rollup-plugin-livereload pull request #84
Opened 2023-08-07 22:58 UTC by thgh

These are just some basic tests, but they are automated and provide an kickstart to build upon.

2023-08-14 17:01 UTC, jonkoops requested changes

2023-08-14 17:01 UTC, jonkoops commented on test/config/entry.js
> +    '<br>Path: ' + window.location.pathname + '<br>Dadte: ' + Date.now())
Small typo here.
```suggestion
    '<br>Path: ' + window.location.pathname + '<br>Date: ' + Date.now())
```

2023-08-15 07:56 UTC, thgh commented on .github/workflows/pr.yml
> +      - run: yarn install
It does, see https://github.com/thgh/rollup-plugin-livereload/actions/runs/5790693158/job/15694230413

2023-08-15 07:59 UTC, thgh commented on package.json
> +    "rollup": "3",
It's a dev dependency, so this is not installed on the users machine. The code does not depend on rollup so it's not a peerDependency either

2023-08-15 08:01 UTC, thgh commented on package.json
> +    "@rollup/plugin-node-resolve": "^9.0.0",
Thanks, will fix!

2023-08-15 08:04 UTC, thgh commented on .github/workflows/pr.yml
> +      - run: yarn install
Advantage of leaving it out is that the action runs using the same dependencies as the ones users will have, so if a breaking update to livereload comes out, we will know.

Will add  --frozen-lockfile (equivalent flag for yarn v1)

2023-08-15 08:08 UTC, thgh commented on package.json
> +    "vitest": "^0.34.1"
Feel free to refactor in @rollup/plugins repo, I just used what I know

2023-08-15 10:53 UTC, thgh commented on .github/workflows/pr.yml
> +      - run: yarn test
Hmm, it's not working, will remove for now, but it can be added afterwards!

2023-08-15 17:41 UTC, jonkoops approved these changes

2023-08-15 20:13 UTC, merged